export type LoaderMeta = {
  slug: string;
  name: string;
  tagline: string;
  /** What the component is, in one paragraph. */
  about: string;
  /** Points worth reading before copying it. */
  notes: string[];
  /** Keyboard controls, shown verbatim. */
  keys: string;
  file: string;
  /** Raw source, served from /loader-source/<file> and fetched on demand. */
  raw: string;
  importLine: string;
};

export const loaders: LoaderMeta[] = [
  {
    slug: "lab-run",
    name: "Lab Run",
    tagline: "Pixel runner loader",
    about:
      "A white lab mouse runs a shelf and jumps the pills in its way, getting faster the longer the wait lasts. Every sprite is built from code at startup — ellipses and runs of pixels drawn into a grid — so the whole thing ships as one file with no image assets at all.",
    notes: [
      "Sprites are generated, not drawn: no PNG, no sprite sheet, nothing to load before the loader can appear.",
      "Jump height responds to how long the key is held, so the control has range rather than one fixed arc.",
      "Takes focus on mount, so the keyboard works without clicking first — turn autoFocus off if it is not the main thing on screen.",
      "Honours prefers-reduced-motion, and the status region announces politely rather than interrupting.",
    ],
    keys: "Space / Up / W jump (hold for height) · Down / S duck",
    file: "LabRunLoader.jsx",
    raw: "/loader-source/LabRunLoader.jsx",
    importLine: 'import { LabRunLoader } from "@/ui/LabRunLoader";',
  },
  {
    slug: "pill-shot",
    name: "Pill Shot",
    tagline: "Canvas arcade loader",
    about:
      "Drag back and release to shoot pills into the bottle. The whole scene is drawn on a canvas in a fixed 1000×700 world and scaled to fit, so it stays crisp at any size and ships no image assets — the component is one file with no dependencies beyond React.",
    notes: [
      "Physics runs on a fixed timestep with three substeps, so the arc is identical regardless of frame rate.",
      "Honours prefers-reduced-motion, and re-checks it on change rather than only at mount.",
      "Cover a request that is genuinely in flight. A loader over an absent call reads as a broken page.",
    ],
    keys: "Up/Down aim · Left/Right power · Space shoot",
    file: "PillShotLoader.jsx",
    raw: "/loader-source/PillShotLoader.jsx",
    importLine: 'import { PillShotLoader } from "@/ui/PillShotLoader";',
  },
  {
    slug: "pill-sort",
    name: "Pill Sort",
    tagline: "SVG sorting puzzle loader",
    about:
      "Tap a bottle to pick up its top run of pills, tap another to drop them. A pill moves only onto an empty bottle or onto its own kind. Drawn as a single inline SVG in the same 1000×700 world, so it scales without a canvas and stays selectable by assistive tech.",
    notes: [
      "Every board is proved solvable before it is shown — levels are generated by shuffling from a solved state, never at random and checked after.",
      "Pills carry a printed imprint as well as two tones, so they are separable without relying on colour.",
      "Moves are announced through a live region, and the puzzle is fully playable from the keyboard.",
      "Boards are generated in an effect rather than during render, so server and client markup agree.",
    ],
    keys: "Left/Right choose · Enter pick up and drop · U undo",
    file: "PillSortLoader.jsx",
    raw: "/loader-source/PillSortLoader.jsx",
    importLine: 'import { PillSortLoader } from "@/ui/PillSortLoader";',
  },
];
